### ISSUE TITLE
Lab 02- Submissions Question 

### ISSUE THREAD

**Issue by AmyTrumpower** [Watts-College/cpp-527-fall-2021#5]
Hi Dr. Lecy:
I was wondering if I could break up Lab 2 into 2 RMD files; one for Part 1 and one for Part 2. The file is getting unwieldly in R-Studio. I was not sure if practicing navigating a lengthy program was part of the "R Adventure" or if there would be any impact to future assignments.

Thank you in advance,
Amy

**Comment by lecy** [comment]
Unwieldy in length of the document or time it takes to run? 

The table of contents (TOC) features in RMD docs comes in handy for navigating longer files. Be sure to use headers to create proper anchors.

```
# part 1
## question 1
etc
```

```
---
output:
  html_document:
    theme: readable
    highlight: tango
    toc: true
    toc_float: true
---
```

Figuring out how to keep all of the parts organized in your head (packages, data, functions, documents) and in your RMD file is a huge part of the learning curve!
